name: Test

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  bench:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: ./configure
      - name: make
        run: make
      - name: run main
        run: ./main
